### ISSUE TITLE
Environment setup (jnorris)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#1]
1) Download repo, develop branch
2) Create a virtualenv with python2.6 
3) Install protobuf runtime locally (from an OS package, or from the download with autogen+configure+make)
4) Install into the virtualenv the library for development, using "setup.py develop" ath the python directory of the repo
5) Check that everithing works with "setup.py test"

**Comment by ramiro** [comment]
En #2 dejé un mini-instructivo por si sirve.
