### ISSUE TITLE
Environment setup (rmorales)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#2]
1) Download repo, develop branch
2) Create a virtualenv with python2.6
3) Install protobuf runtime locally (from an OS package, or from the download with autogen+configure+make)
4) Install into the virtualenv the library for development, using "setup.py develop" ath the python directory of the repo
5) Check that everithing works with "setup.py test"

**Comment by ramiro** [comment]
En Ubuntu 12.04 (los comandos marcados con `*` son específicos de mi setup):

3)

```
$ sudo add-apt-repository ppa:fkrull/deadsnakes
$ sudo apt-get update && sudo apt-get install python2.6 python2.6-dev
```

2)

```
$ mkproject -p python2.6 protobuf-py3
```

1)

```
(protobuf-py3)$ python --version
Python 2.6.8
(protobuf-py3)$ git clone https://ramiro@github.com/machinalis/protobuf-python3.git
(protobuf-py3)$ cd protobuf-python3
(protobuf-py3)$ git config user.email user@example.com        # *
(protobuf-py3)$ git checkout -b develop origin/develop
(protobuf-py3)$ git branch
develop
```

  Es posible que en este punto  debamos crear nuestro branch de trabajo para trabajar en un issue en particular. Por ej.:

```
(protobuf-py3)$ git checkout -b issue4
(protobuf-py3)$ git branch
issue4
```

4)

```
(protobuf-py3)$ cd python
(protobuf-py3)$ python setup.py develop
```

5)

```
(protobuf-py3)$ python -3 setup.py test
...
----------------------------------------------------------------------
Ran 193 tests in 0.318s

OK
```
