### ISSUE TITLE
Check if changes are needed in installer (setup/ez_setup)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#22]
With the current fixes, "python setup.py develop" works in python 3, but it would be nice to check that we're following the reasonable steps to make this installable in python3 (specially because ez_setup uses urllib, should it do that?)

**Comment by juannorris** [comment]
After some reading I've found that ez_setup.py should be replaced with [distribute_setup.py](http://pypi.python.org/pypi/distribute), which contains things like conditional imports on python version used.
I've tried distribute with this commands:

python setup.py test/develop/install/build

and everything seems to work.

TODO:
- Install distribute.
  In [setup.py](https://github.com/machinalis/protobuf-python3/blob/develop/python/setup.py):
- Replace ez_setup with distribute_setup
- Add python3 to classifiers

**Comment by juannorris** [comment]
Fixed in b065c461ac4817f30b25b826ef9e8c652afac75d.
