### ISSUE TITLE
Remove unicode() calls

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#25]
Some of them are being used to decode bytes (as in unicode(data, 'utf-8'); that should be replaced with data.decode('utf-8')); others as isinstance argument, which probably should be replaced with six.text_type. Sometimes unicode('literal') is used, which should just be u'literal' (which will be replaced to 'literal' later, when we work on #16)

**Comment by ramiro** [comment]
Fixed in 6382ee348579bbf6b473169718b5263d1742e395.

I went ahead and worked on this one because #16 somewhat depends on this.

Reviews welcome.

**Comment by juannorris** [comment]
Oh I have already started working on this one yesterday, but that's ok. Seems right to me, but added a comment about str https://github.com/machinalis/protobuf-python3/commit/6382ee348579bbf6b473169718b5263d1742e395#L2L117

**Comment by ramiro** [comment]
@juann9 

Thanks!

I missed `binary_type` from `six` documentation. I used the fact that in Python 2.6 `bytes` exists and is an alias for `str`, so in these cases (calls to `isinstance()`, also searched for `issubclass()`) I simply performed a `s/str/bytes/` replacement.

We can discuss this on Monday with dmoisset.

**Comment by juannorris** [comment]
Oh ok, I didn't know that.
