### ISSUE TITLE
Review uses of ord()

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#30]
There are some uses of ord to convert a byte in a byte buffer to an int, when in py3 just indexing the buffer returns an int. so doing something lide ord(buffer[3]) where buffer is fo types bytes(0 will fail in py3

**Comment by dmoisset** [comment]
pushed in e1efc37

**Comment by ramiro** [comment]
I meant to add a comment saying that instances of this error have reappeared. I intend to work on them.

**Comment by dmoisset** [comment]
Fixed in 4ef184c
