### ISSUE TITLE
Check how to replace string_escape

### ISSUE THREAD

**Issue by juannorris** [machinalis/protobuf-python3#46]
On Python 3.x, the string_escape encoding no longer exists, since str can only store Unicode.

This is used, for example in [here](https://github.com/machinalis/protobuf-python3/blob/develop/python/google/protobuf/text_format.py#L660). 

We should check how to replace this, since there isn't an alias.

Info:
http://stackoverflow.com/questions/2969044/python-string-escape-vs-unicode-escape
http://stackoverflow.com/questions/6867588/how-to-convert-escaped-characters-in-python
http://stackoverflow.com/questions/9327993/python3-unicode-escape-doesnt-work-with-non-ascii-bytes

**Comment by dmoisset** [comment]
Fixed in f9fd79e ; I just realized that the branch name is wrong (39-string_escape instead of 46-string_escape)
