### ISSUE TITLE
use new "except E as v" syntax

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#8]
Everywhere where the old "except E,v" syntax is used

**Comment by dmoisset** [comment]
Fixed. Also included a unicode related fix inside a try/except UnicodeDecodeError

**Comment by juannorris** [comment]
Found some more occurrences.

**Comment by juannorris** [comment]
Checked using:

rgrep except [a-zA-Z0-9_ ]*[,]

Fixed in 06397bbf0604c7862d339e9f4f3bd776d66b9011.
