### ISSUE TITLE
use conditional imports for urllib renamings

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#9]
Several members inside urllib/urllib2/urlparse python2 modules have been moved in python3. Find those uses and wrap with try... except ImportError to use the right one in each case

**Comment by ramiro** [comment]
There doesn't seem to be any use of these modules/functions in the code itself (AFAICT there is only one appearance in the `ez_setup.py` file but I don't think we should touch that)?

**Comment by dmoisset** [comment]
I'm not sure, but ok, let's close this now. I opened an issue specifically related to the setup process
